# Generated by Django 2.2.5 on 2019-09-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treebanks', '0002_sentence_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='lemma',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='postag',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
