# Generated by Django 2.2.5 on 2019-09-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treebanks', '0003_auto_20190914_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='relation',
            field=models.CharField(max_length=16),
        ),
    ]
